HOME_FACTURALUX = /usr/local/facturalux
HOME_FLPROTOTIPO = ${HOME_FACTURALUX}/flprototipo-formacion

REPORTS = actividadeslaborales.kut \
          certificado.kut \
          cursos.kut \
          personas.kut \
          sectoreslaborales.kut \
          alumnosxcurso.kut \
          xunta.kut

install:
	scp $(REPORTS) root@auden:$(HOME_FLPROTOTIPO)/share/facturalux/reports

uninstall:
#	rm 
#	$(MAKE) -C $(HOME_XCERELL)/src clean
#	rm -f bin/xcerell Makefile~
#	rm -f ../Resultados-xcerell/fich_*.txt

